services:
  app:
    image: maacosv/backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_HOST: mysql
      MYSQL_DATABASE: jumpStart
      MYSQL_PORT: 3306
      JWT_KEY: secret
      ENCRYPT_KEY: 5c03KCxiS0FvfOH3
      PASSWORD_EMAIL: PASSWORD_EMAIL
      ADRESS_EMAIL: ADRESS_EMAIL

  python-app:
    image: maacosv/python-datas:latest
    container_name: jump-start-python
    restart: always 
    working_dir: /app  
    command: python main.py 
    environment:
      url: URL_GOOGLE_SHEETS
      URL_BACKEND: http://localhost:8080/
      NAME_DATABASE: jumpStart
      PASSWORD_DATABASE: password
      USER_DATABASE: root
      HOST_DATABASE: mysql  

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jumpStart
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data: